name: Check Push

on:
  push:
    branches: [ "recrutamento**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install
      run: npm install

    - name: Test
      run: npm run test